# Generated by Django 5.1.7 on 2025-06-06 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата и время измерения")),
                ("hr", models.PositiveSmallIntegerField(verbose_name="Пульс (уд/мин)")),
                (
                    "br",
                    models.PositiveSmallIntegerField(verbose_name="Дыхание (дых/мин)"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Измерение",
                "verbose_name_plural": "Измерения",
                "ordering": ["-date"],
            },
        ),
    ]
