# Generated by Django 5.1.7 on 2025-06-08 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_healthmeasurement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthmeasurement",
            options={
                "ordering": ["-date"],
                "verbose_name": "Измерение",
                "verbose_name_plural": "Измерения",
            },
        ),
        migrations.RemoveField(
            model_name="healthmeasurement",
            name="breathing_rate",
        ),
        migrations.RemoveField(
            model_name="healthmeasurement",
            name="heart_rate",
        ),
        migrations.RemoveField(
            model_name="healthmeasurement",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="healthmeasurement",
            name="br",
            field=models.PositiveSmallIntegerField(
                default=0.0, verbose_name="Дыхание (дых/мин)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthmeasurement",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата и время измерения"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthmeasurement",
            name="hr",
            field=models.PositiveSmallIntegerField(
                default=0.0, verbose_name="Пульс (уд/мин)"
            ),
            preserve_default=False,
        ),
    ]
