# Generated by Django 5.1.7 on 2025-06-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videodelivery', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='head_position',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='breathing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pulse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
